name: Mirroring

on: [push, delete]

jobs:
  mirror:
    runs-on: ubuntu-18.04
    steps:                            
    - uses: actions/checkout@v1
    - uses: spyoungtech/mirror-action@master
      with:
        REMOTE: 'git@github.com:jMonkeyEngine/jmonkeyengine-webservices-discordbot.git'
        GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
        GIT_SSH_NO_VERIFY_HOST: "true"